all:
	rm -f out.*
	rm -f *.json
	./runpbp dtree-transmogrifier.drawio ../../pbp xinterpret.drawio


install:
	npm install yargs prompt-sync ohm-js @xmldom/xmldom

clean:
	rm -f out.*
	rm -f *.json
	rm -f junk.* temp.*
