#!/bin/bash
set -e
src_drawing="$(./realpath.py $1)"
export SRC_DRAWING_PATH="$(dirname ${src_drawing})"
export PBP_LIB="$(./realpath.py $2)"
arg="$3"

export PBP_KERNEL_PATH="${PBP_LIB}/kernel"
export PBP_DAS_PATH="${PBP_LIB}/das"

export PYTHONPATH="${PBP_KERNEL_PATH}:$PYTHONPATH"
export PBP_SPLITOUTJS="${PBP_LIB}/kernel/splitoutput.js"
export PBP_T2T="${PBP_LIB}/t2t.bash"

cd "${SRC_DRAWING_PATH}"
node "${PBP_LIB}/das/das2json.mjs" "${src_drawing}"
./check-for-span-error.bash  ${src_drawing}.json
python main.py "${PBP_LIB}" "${arg}" main  "${src_drawing}.json" >/tmp/xyz
node "${PBP_SPLITOUTJS}" </tmp/xyz
if [ -f out.✗ ]
then
    cat out.✗
    echo
    exit 1
fi

